# Generated by Django 2.1.7 on 2019-02-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190220_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='skills_list',
        ),
        migrations.AddField(
            model_name='offer',
            name='skills_list',
            field=models.TextField(default='django, doker , graghQl'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
