# Generated by Django 2.1.7 on 2019-02-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190225_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='user_id',
            new_name='user',
        ),
    ]
