# Generated by Django 2.1.7 on 2019-02-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190225_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
