# Generated by Django 2.1 on 2019-03-05 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190304_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='skills_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), size=None),
        ),
    ]
